version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python manage.py migrate
      - python manage.py collectstatic --noinput

  post_build:
    commands:
      - python manage.py test

artifacts:
  files:
    - '**/*'
  base-directory: 'staticfiles'
